#cloud-config
users:
  - name: ${ssh_username}
    ssh-authorized-keys:
      - ssh-ed25519 ${public_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
packages:
  - ntpdate
  - wget
ntp:
  enabled: true
  ntp_client: chrony
